# Generated by Django 4.1 on 2023-03-14 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MedApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='date_of_research',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='photo',
            name='researcher',
            field=models.IntegerField(null=True),
        ),
    ]
