# Generated by Django 4.1 on 2022-12-28 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MedApp', '0002_alter_photo_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='diagnosys',
            field=models.CharField(max_length=10000, null=True),
        ),
    ]
