# Generated by Django 4.1 on 2022-12-28 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MedApp', '0003_photo_diagnosys'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='diagnosys',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='number_of_instance',
        ),
        migrations.AddField(
            model_name='photo',
            name='date_of_creation',
            field=models.DateField(null=True),
        ),
    ]
