# Generated by Django 4.1 on 2022-12-31 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MedApp', '0005_alter_photo_date_of_creation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photo',
            options={'ordering': ['patient_number_id', '-date_of_creation']},
        ),
        migrations.RenameField(
            model_name='photo',
            old_name='diagnosys',
            new_name='diagnosis',
        ),
    ]
