# Generated by Django 4.1.4 on 2023-01-03 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MedApp', '0006_alter_photo_options_rename_diagnosys_photo_diagnosis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='photo',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
